#!/bin/sh
# /etc/init.d/s-w-e-a-t

### BEGIN INIT INFO
# Provides:          s-w-e-a-t
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts s-w-e-a-t at boot
# Description:       Initscript for S.W.E.A.T project. Inspired from www.stuffaboutcode.com
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting s-w-e-a-t"
    cd /opt/s-w-e-a-t
    /usr/bin/java -Dpi4j.linking=dynamic -jar sweat-*.jar &
    ;;
  stop)
    echo "Stopping s-w-e-a-t"
    killall java
    ;;
  *)
    echo "Usage: /etc/init.d/s-w-e-a-t {start|stop}"
    exit 1
    ;;
esac

exit 0 
